-- =============================================================
-- Prices App: unidades de medida
-- Ejecutar después de 001_roles_rls.sql. Es idempotente.
-- =============================================================

create table if not exists public.units_measures (
    id            bigint generated by default as identity primary key,
    name          text not null unique,
    abbreviation  text not null unique
);

insert into public.units_measures (name, abbreviation) values
    ('Unidad', 'u'),
    ('Kilogramo', 'kg'),
    ('Gramo', 'g'),
    ('Libra', 'lb'),
    ('Litro', 'L'),
    ('Mililitro', 'ml'),
    ('Galón', 'gal'),
    ('Paquete', 'paq'),
    ('Docena', 'doc'),
    ('Caja', 'caja')
on conflict do nothing;

alter table public.products
    add column if not exists unit_id bigint
        references public.units_measures (id) on delete restrict;

-- ---------- RLS: units_measures ----------
alter table public.units_measures enable row level security;

drop policy if exists "units_select_authenticated" on public.units_measures;
create policy "units_select_authenticated" on public.units_measures
    for select to authenticated
    using (true);

drop policy if exists "units_write_admin" on public.units_measures;
create policy "units_write_admin" on public.units_measures
    for all to authenticated
    using (public.is_admin())
    with check (public.is_admin());

-- El empleado tampoco puede cambiar la unidad de medida
create or replace function public.products_guard_update()
returns trigger
language plpgsql
as $$
begin
    if not public.is_admin() then
        if new.name is distinct from old.name
           or new.price is distinct from old.price
           or new.unit_id is distinct from old.unit_id
           or new.id is distinct from old.id then
            raise exception 'Solo un administrador puede cambiar nombre, precio o unidad'
                using errcode = '42501';
        end if;
    end if;
    return new;
end;
$$;
